const dummyClients = [
  {
    client: "1",
    npsGrade: 10,
    shippingValue: true,
    price: true,
    navigation: true,
    payment: true,
    delivery: true,
  },
  {
    client: "2",
    npsGrade: 7,
    shippingValue: false,
    price: false,
    navigation: false,
    payment: true,
    delivery: true,
  },
  {
    client: "3",
    npsGrade: 8,
    shippingValue: true,
    price: false,
    navigation: false,
    payment: true,
    delivery: true,
  },
  {
    client: "4",
    npsGrade: 6,
    shippingValue: true,
    price: false,
    navigation: true,
    payment: true,
    delivery: true,
  },
  {
    client: "5",
    npsGrade: 8,
    shippingValue: true,
    price: false,
    navigation: false,
    payment: true,
    delivery: true,
  },
  {
    client: "6",
    npsGrade: 8,
    shippingValue: true,
    price: false,
    navigation: false,
    payment: true,
    delivery: true,
  },
  {
    client: "7",
    npsGrade: 7,
    shippingValue: false,
    price: false,
    navigation: false,
    payment: false,
    delivery: false,
  },
];

export default dummyClients;

